version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cache
      POSTGRES_USER: pgcache
      POSTGRES_PASSWORD: password

# pgcache:
#   postgres:
#     driver: bridge
